package commands

import (
	"fmt"
	"os"

	"discord-iac/internal/config"
	"gopkg.in/yaml.v3"
)

// InitCommand generates a default bot.yaml file in the current directory
func InitCommand() error {
	filename := "bot.yaml"

	if _, err := os.Stat(filename); err == nil {
		return fmt.Errorf("%s already exists in the current directory", filename)
	}

	cfg := config.DefaultBotConfig()
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to marshal default config: %w", err)
	}

	// Add some comments to the top
	header := []byte("# Discord Bot Architecture Configuration\n# Generated by discord-iac\n\n")
	data = append(header, data...)

	err = os.WriteFile(filename, data, 0644)
	if err != nil {
		return fmt.Errorf("failed to write %s: %w", filename, err)
	}

	fmt.Printf("Successfully generated %s! Edit it and run `discord-iac generate`.\n", filename)
	return nil
}
